"""Metadata + agent-discovery routes for the Methodex public website.

GET /metadata/manifest.json   the machine-readable public coverage descriptor
                              (relocated from /download/* per DOWNLOAD_AND_FORMATS
                              DNA — a coverage descriptor is metadata, not a data
                              download; JSON is allowed ONLY under a /metadata/
                              path, never under /download/*).
GET /llms.txt                 the agent-first site map (kit CDF make_llms_txt output),
                              listing the data/code bundles + the MCP endpoint.

The old GET /download/manifest.json now 308-redirects here (see downloads.py).
"""
from __future__ import annotations

import logging

from fastapi import APIRouter, HTTPException
from fastapi.responses import PlainTextResponse, Response

from app import config as C
from app.services import download_service as DL

logger = logging.getLogger(__name__)
router = APIRouter(tags=["meta"])

_JSON = "application/json; charset=utf-8"


@router.get("/metadata/manifest.json")
def metadata_manifest() -> Response:
    """The machine-readable public coverage manifest (metadata, not a dataset
    download). Public-domain coverage descriptor only."""
    try:
        raw, media, filename = DL.export_manifest()
    except Exception as exc:  # noqa: BLE001
        logger.exception("metadata manifest failed")
        raise HTTPException(status_code=500, detail=str(exc)) from exc
    # Inline (not attachment): this is a machine-readable descriptor, not a download.
    return Response(content=raw, media_type=media,
                    headers={"Cache-Control": "public, max-age=300"})


@router.get("/llms.txt", response_class=PlainTextResponse)
def llms_txt() -> PlainTextResponse:
    """The agent-first site map. Served from the vendored static llms.txt so the
    file is byte-stable and reproducible (generated by the kit make_llms_txt.py
    from ecosystem.json + a methodex MCP section)."""
    p = C.STATIC_DIR / "llms.txt"
    if not p.exists():
        raise HTTPException(status_code=404, detail="llms.txt not generated")
    return PlainTextResponse(p.read_text(encoding="utf-8"),
                             media_type="text/plain; charset=utf-8")
